CREATE TABLE IF NOT EXISTS compras (
ID_compra INT AUTO_INCREMENT PRIMARY KEY,
Fecha DATE,
Monto DECIMAL(10,2),
Comercio VARCHAR(30),
Tipo VARCHAR(40),
Cantidad_productos INT,
ID_gasto INT
);

CREATE TABLE IF NOT EXISTS producto (
ID INT AUTO_INCREMENT PRIMARY KEY,
Producto VARCHAR(40),
ID_producto INT,
Costo DECIMAL(10,2),
Cantidad DECIMAL(10,2),
ID_compra INT,
ID_gasto INT
);

CREATE TABLE IF NOT EXISTS productos(
ID_producto INT AUTO_INCREMENT PRIMARY KEY,
Producto VARCHAR(40)
);

CREATE TABLE IF NOT EXISTS ingresos (
ID INT AUTO_INCREMENT PRIMARY KEY,
Fecha DATE,
Monto DECIMAL(10,2),
Concepto VARCHAR(40)
);

CREATE TABLE IF NOT EXISTS gastos (
ID_gasto INT AUTO_INCREMENT PRIMARY KEY,
Fecha DATE,
Monto DECIMAL(10,2),
Concepto VARCHAR(40)
);

CREATE TABLE IF NOT EXISTS deuda(
    ID_deuda INT AUTO_INCREMENT PRIMARY KEY,
    Fecha DATE,
    Monto DECIMAL (10,2),
    Prestamista VARCHAR(20),
    Prestatario VARCHAR(20),
    Tasa DECIMAL (4,2)
);
